version: '3'

services:

  db:
    image: postgres:10
    volumes:
      - pgdata1:/var/lib/postgresql/data

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  web:
    build: .
    command: ./update_static_run.sh
    volumes:
      - .:/app
    ports:
      - "8003:8000"
    depends_on:
      - db
    restart: always
    environment:
      - POSTGRES_HOST=db
    env_file:
      - ./env.secret

volumes:
    pgdata1:
    front:

