version: '3'

services:

  db:
    image: postgres:10
    volumes:
      - pgdata:/var/lib/postgresql/data

    environment:
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    restart: on-failure
    volumes: 
      - .:/app
    ports:
      - "8003:8000"
    depends_on:
      - db

    env_file:
      - ./env.secret
   
volumes:
    pgdata:
