# Generated by Django 3.2 on 2021-04-16 15:08

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquery', models.CharField(max_length=100)),
                ('annex_num', models.PositiveIntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AnnexRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('annex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='api.annex')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_voen', models.PositiveBigIntegerField(unique=True)),
                ('account_num', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('swift', models.PositiveIntegerField()),
                ('banking_code', models.PositiveIntegerField()),
                ('bank_voen', models.PositiveBigIntegerField(unique=True)),
                ('reporter_account', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClientConnectDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_person', models.CharField(max_length=50)),
                ('telephone_num', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('work_email', models.EmailField(max_length=254)),
                ('personal_email', models.EmailField(max_length=254)),
                ('web_site', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(max_length=255)),
                ('delivery', models.CharField(max_length=255)),
                ('handed', models.CharField(max_length=255)),
                ('custom_condition', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('plant_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalesManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit_price', models.PositiveIntegerField()),
                ('total_price', models.PositiveIntegerField()),
                ('annex_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='api.annexrevision')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_num', models.PositiveBigIntegerField(unique=True)),
                ('client_company_name', models.CharField(max_length=100)),
                ('contract_type', models.CharField(max_length=100)),
                ('legal_address', models.CharField(max_length=255)),
                ('boss_name', models.CharField(max_length=50)),
                ('boss_surname', models.CharField(max_length=50)),
                ('boss_middle_name', models.CharField(max_length=50)),
                ('created_date', models.DateField()),
                ('expired_date', models.DateField()),
                ('process_status', models.CharField(max_length=20)),
                ('sales_manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.salesmanager')),
            ],
        ),
        migrations.AddField(
            model_name='annex',
            name='buyer',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.buyer'),
        ),
        migrations.AddField(
            model_name='annex',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annex_list', to='api.contract'),
        ),
        migrations.AddField(
            model_name='annex',
            name='current_revision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_annex', to='api.annexrevision'),
        ),
        migrations.AddField(
            model_name='annex',
            name='plant',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.plant'),
        ),
        migrations.AddField(
            model_name='annex',
            name='sales_manager',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.salesmanager'),
        ),
    ]
