# Generated by Django 3.2 on 2021-04-19 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_person', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('work_email', models.EmailField(max_length=254)),
                ('personal_email', models.EmailField(max_length=254)),
                ('web_site', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('legal_address', models.CharField(max_length=255)),
                ('created_date', models.DateField()),
                ('expired_date', models.DateField()),
                ('num', models.PositiveBigIntegerField(unique=True)),
                ('director_name', models.CharField(max_length=50)),
                ('director_surname', models.CharField(max_length=50)),
                ('director_middle_name', models.CharField(max_length=50)),
                ('sales_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salesmanager')),
            ],
        ),
        migrations.DeleteModel(
            name='ClientConnectDataModel',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='bank_voen',
            new_name='voen',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='client_voen',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='boss_middle_name',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='boss_name',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='boss_surname',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='client_company_name',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_num',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='expired_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='legal_address',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='process_status',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='sales_manager',
        ),
        migrations.AddField(
            model_name='contract',
            name='bank',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bank'),
        ),
        migrations.AddField(
            model_name='contract',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customuser'),
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'In progress'), (1, 'Approved'), (2, 'Time over')], default=0, verbose_name='Contract status'),
        ),
        migrations.AddField(
            model_name='contract',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Buy-sale'), (1, 'One time'), (2, 'Distributor'), (3, 'Service')], default=0, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='annexrevision',
            name='annex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='api.annex'),
        ),
        migrations.AlterField(
            model_name='product',
            name='annex_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.annexrevision'),
        ),
        migrations.AddField(
            model_name='contract',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.client'),
        ),
        migrations.AddField(
            model_name='contract',
            name='entity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.entity'),
        ),
    ]
