# Generated by Django 3.2.2 on 2021-05-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210516_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseannex',
            name='annex_no',
            field=models.IntegerField(default=1),
        ),
    ]
