# Generated by Django 3.2.2 on 2021-05-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210520_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tin',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='TIN'),
        ),
    ]
