# Generated by Django 3.2.2 on 2021-05-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_rentconditions_annex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseannex',
            name='request_no',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
