# Generated by Django 3.2.2 on 2021-05-23 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_baseannex_request_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='company_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_acc_list', to='api.company'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='personal_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_acc_list', to='api.person'),
        ),
    ]
