# Generated by Django 3.2.3 on 2021-06-08 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210523_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.basecontract')),
            ],
        ),
    ]
