# Generated by Django 3.2.2 on 2021-06-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210608_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseannex',
            name='request_no',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
