# Generated by Django 3.2.2 on 2021-06-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_baseannex_request_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradeAgreementAnnex',
        ),
    ]
