# Generated by Django 3.2.2 on 2021-06-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_delete_tradeagreementannex'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseannex',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
