# Generated by Django 3.2.2 on 2021-06-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210625_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeagreement',
            name='final_amount_with_writing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onetimeagreement',
            name='part_acquisition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onetimeagreement',
            name='part_payment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onetimeagreement',
            name='price_offer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onetimeagreement',
            name='price_offer_validity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onetimeagreement',
            name='standard',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onetimeagreement',
            name='unpaid_period',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onetimeagreement',
            name='unpaid_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onetimeagreement',
            name='warranty_period',
            field=models.TextField(blank=True, null=True),
        ),
    ]
