# Generated by Django 3.2.2 on 2021-07-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210629_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseannex',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'In process'), (1, 'Approved'), (2, 'Canceled')], default=0),
        ),
    ]
