# Generated by Django 3.2.2 on 2021-07-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_contact_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecontract',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'In process'), (1, 'Approved'), (2, 'Expired'), (4, 'Canceled')], default=0),
        ),
    ]
