# Generated by Django 3.2.6 on 2021-08-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_customertemplateagreement_custom_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseannex',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productinvoiceitem',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productinvoiceitem',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rentitems',
            name='total',
            field=models.FloatField(),
        ),
    ]
